# Generated by Django 4.2.11 on 2024-05-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_road', models.CharField(default='NA', max_length=150)),
                ('subject', models.CharField(default='NA', max_length=150)),
                ('details', models.CharField(default='NA', max_length=150)),
                ('location', models.CharField(default='NA', max_length=150)),
                ('state', models.CharField(default='NA', max_length=150)),
                ('city', models.CharField(default='NA', max_length=150)),
                ('postel_code', models.IntegerField(default=0)),
                ('images', models.ImageField(blank=True, null=True, upload_to='user')),
                ('email', models.EmailField(default='NA', max_length=254)),
            ],
        ),
    ]
