# Generated by Django 4.2.11 on 2024-05-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_form_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='staus',
            field=models.CharField(default='NA', max_length=150),
        ),
    ]
