# Generated by Django 4.2.11 on 2024-05-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_form_staus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='staus',
            field=models.CharField(default='Pending', max_length=150),
        ),
    ]
